lastupdatecheck: 0
recentrepos:
    - /Users/tk4o2ka/github/blog
    - /Users/tk4o2ka/dotfiles
startuppopupversion: 5
lastversion: 0.43.1
customcommandshistory:
    - q
    - qa
hidecommandlog: true
ignorewhitespaceindiffview: false
diffcontextsize: 3
renamesimilaritythreshold: 50
localbranchsortorder: recency
remotebranchsortorder: alphabetical
gitlogorder: topo-order
gitlogshowgraph: always
